# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-26 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20160628_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(editable=False, help_text='Short, randomish identifier used in the URL of a project.', unique=True),
        ),
    ]
