# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-26 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20160926_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, help_text='The title of the note (optional).', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set([]),
        ),
    ]
