var _ = require('underscore');

module.exports = _.template(''
  + '<h5>Common item types:</h5>'
  + ''
  + '<% if (common) { %>'
  + '<ul class="unstyled common-item-types">'
    + '<% common.slice(0, 6).forEach(function (commonType) { %>'
    + '<% var type = _.findWhere(itemTypes, { itemType: commonType }) %>'
    + '<li><a href="#" data-item-type="<%= type.itemType %>"><%= type.localized %></a></li>'
    + '<% }) %>'
  + '</ul>'
  + '<% } %>'
  + ''
  + '<h5>All types</h5>'
  + '<select class="item-type-select">'
    + '<% itemTypes.forEach(function (type) { %>'
    + '<option value="<%= type.itemType %>"><%= type.localized %></option>'
    + '<% }) %>'
  + '</select>')
